### ISSUE TITLE
TAB全部关闭后显示错误

### ISSUE THREAD

**Issue by w-zhCN** [build-admin/buildadmin#10]
在控制台页面选择关闭全部标签

![image](https://user-images.githubusercontent.com/64721308/204130033-70c8f33c-86a7-4faa-b20d-53ef5b96cb61.png)
![image](https://user-images.githubusercontent.com/64721308/204130034-72d57c13-5e7e-422b-9247-f6b363acbc0e.png)

**Comment by build-admin** [comment]
问题已复现。感谢反馈~
