### ISSUE TITLE
请问一下这个在表格中自定义输入框为什么会报错

### ISSUE THREAD

**Issue by 964562398** [build-admin/buildadmin#12]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/11940269/206871903-5a78b41b-682b-4662-b3d8-b29ce2c7bec8.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/11940269/206871947-97088082-9c28-4aa8-a83e-5ba2b159f69b.png">

**Comment by 964562398** [comment]
如果不写onUpdate:modelValue，输入框无法输入数据

**Comment by build-admin** [comment]
modelValue不是双向绑定
