### ISSUE TITLE
Info project...

### ISSUE THREAD

**Issue by tecnoweb** [build-admin/buildadmin#17]
안녕하세요, 저는 현재 https://xcrud.net/을 사용하고 있는 처음부터 귀하의 프로젝트를 좋아했습니다. 그러나 나는 당신의 프로젝트에 모든 것을 가져오고 싶지만 관계 하위 선택, 중첩 및 여기에 있는 다른 기능을 수행하는 것이 가능합니까?

프로젝트 축하합니다

Hi, I loved your project right from the start I currently use https://xcrud.net/. but I would like to bring it all to your project but is it possible to do relation subselect,nested and other functions present here?

Congratulations on your project

**Comment by build-admin** [comment]
I don't know much about xcrud, but nothing is impossible, if you have enough time and confidence, please feel free to do it

**Comment by tecnoweb** [comment]
https://xcrud.me/xcrud-documentation/ this is full documentation of xcrud maybe you can do some part off it on our software is the best :)
