### ISSUE TITLE
如何在batable中增加elementui的多级表头,使用customRender函数不作用

### ISSUE THREAD

**Issue by LTAND** [build-admin/buildadmin#19]
https://element-plus.org/zh-CN/component/table.html#%E5%A4%9A%E7%BA%A7%E8%A1%A8%E5%A4%B4

**Comment by build-admin** [comment]
最外层已经渲染了一层el-table-column，所以customRender里边直接渲染嵌套的el-table-column即可，另外表格也有插槽可以使用
