### ISSUE TITLE
希望增加一键生成API文档的功能

### ISSUE THREAD

**Issue by muxik** [build-admin/buildadmin#20]
BuildAdmin是一个前后端分离的后台框架，也就代表着不像传统fastadmin那样所有的事情由后端搞定
既然API服务独立处理了，希望作者可以做一个一键生成API文档的功能（包含系统已有的接口，没有按照约定的注释或者其他东西生成），此功能一旦实现可以更加便于前后端开发人员协同，交流、开发

**Comment by build-admin** [comment]
已有接口值得写文档的只有会员登录注册

**Comment by build-admin** [comment]
感谢建议，目前暂不考虑API文档生成，因为第三方的api调试、文档生成工具较多，而且很完善，而我们来做一个api文档生成需要很多时间，又没有第三方的好用
