### ISSUE TITLE
Composer install 报错

### ISSUE THREAD

**Issue by happydigua** [build-admin/buildadmin#22]
Uncaught Error: Call to undefined method think\Console::addDefaultCommands() in /Users/lv/Documents/vendor/topthink/think-migration/src/config.php:10

**Comment by build-admin** [comment]
这个问题不能复现到哈，确保php版本为8.0+，实在不行使用资源包覆盖或使用完整包吧

**Comment by happydigua** [comment]
"w7corp/easywechat": "*",
        "phpmailer/phpmailer": "*",
        "topthink/think-migration": "3.1.x-dev"

解决了
这几个版本不对，谢谢

**Comment by happydigua** [comment]
可能是 composer 源的问题。。。

**Comment by build-admin** [comment]
了解，不建议使用阿里源，已经不再维护

**Comment by happydigua** [comment]
有没有 sql 文件提供呢，还是直接导入比较快

**Comment by build-admin** [comment]
使用`phinx`管理数据表迁移

**Comment by happydigua** [comment]
> php think migrate:run
exitcode: 255

**Comment by happydigua** [comment]
数据库一直没搞定。。。

**Comment by happydigua** [comment]
php think migrate:run

 == 20230620180908 Install: migrating


                                                                                                                                                      
  [PDOException]                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
