### ISSUE TITLE
建议内置可视化数据权限

### ISSUE THREAD

**Issue by eveinzz** [build-admin/buildadmin#23]
首先感谢作者的佳作，非常棒的产品：

## 一：建议内置可视化数据权限设置项
我已看到目前buildadmin是支持手动在代码中配置数据权限的：https://wonderful-code.gitee.io/senior/server/dataLImit.html

虽然能看懂里边的描述，但如果做成类似这样的：
![WX20230823-140707@2x](https://github.com/build-admin/buildadmin/assets/321913/ce3f7c07-0012-4002-87b1-0cfeb7644dfb)
是否会更直观低代码一些？因为很多场景特别是内管系统都需要做数据权限分级：如（同级、同级以下、仅自己、全部、自定义，无权限）等。是比较常见的通用需求。

## 二：后台管理员表单处修饰字
<img width="1344" alt="image" src="https://github.com/build-admin/buildadmin/assets/321913/42766782-84f3-4781-8518-e6e163d3c227">
这里的“分组”建议用“角色组”，更易理解。

## 三：API接口示例
如果能有一个简单的API介绍及示例，那就更棒了。

**以上，感谢作者！**

**Comment by build-admin** [comment]
感谢建议，关于第三点，建议先看控制器文档，这个是很简单的，内置也有前台会员的相关接口实现

**Comment by build-admin** [comment]
感谢建议，分组已经改为角色组，另外经过考量，CRUD可内置的太多了，内置太多无法保证其简洁，后续这方面需求多，可能会重新考虑内置
