### ISSUE TITLE
样式上的错误

### ISSUE THREAD

**Issue by lowkey-lau** [build-admin/buildadmin#24]
左侧菜单栏的菜单高度是自适应计算的，如果在设置里隐藏logo，菜单栏的高度不会实时刷新，需要切换一下菜单才会重新计算高度

`config.layout.menuShowTopBar`

**Comment by build-admin** [comment]
感谢反馈，问题已复现，但切换LOGO显示隐藏状态后刷新一下就行了，没人会频繁切换LOGO显示状态，另外造成此问题的原因是el的滚动条高度没有随css动态更新造成的
