### ISSUE TITLE
项目隔几天 数据库的字段的 就会变成这样，存的字符串 变成标签啥的了

### ISSUE THREAD

**Issue by code-lives** [build-admin/buildadmin#29]
![image](https://github.com/build-admin/buildadmin/assets/79346591/587a9659-e9f1-4b25-b6bf-6de38d40dc51)

**Comment by build-admin** [comment]
明显是被入侵了哈，可能是服务器被入侵、代码入侵的可能性也有，代码入侵方面，请参考[过滤/反XSS](https://wonderful-code.gitee.io/senior/server/filter.html)
