### ISSUE TITLE
安装 overtrue/wechat 错误

### ISSUE THREAD

**Issue by yang3259** [build-admin/buildadmin#5]
安装 composer require overtrue/wechat:~5.0 -vvv 错误

**Comment by yang3259** [comment]
与  "symfony/http-foundation": "^2.7 || ^3.0 || ^4.0",  冲突

**Comment by build-admin** [comment]
你可以直接把symfony/http-foundation删了，然后只安装overtrue/wechat

**Comment by build-admin** [comment]
记得overtrue/wechat里边是包含symfony/http-foundation的
