### ISSUE TITLE
后台菜单规则管理

### ISSUE THREAD

**Issue by shuqianchi** [build-admin/buildadmin#8]
菜单项 页面内 包含二级页面跳转 如何在菜单规则管理中配置

**Comment by shuqianchi** [comment]
<img width="1714" alt="image" src="https://user-images.githubusercontent.com/26531683/199666754-6530c60a-33b2-478e-b2c9-205faf43d31d.png">
目前是这个样子。如何不展示进度管理的二级页面，并且可以跳转

**Comment by build-admin** [comment]
![image](https://user-images.githubusercontent.com/106626227/199667081-26d12e1f-bd30-4d64-acc2-1d5ec2b68c18.png)
