### ISSUE TITLE
当页面存在 弹窗内也有batable时，操作父页面batable时，方法调用两次

### ISSUE THREAD

**Issue by shuqianchi** [build-admin/buildadmin#9]
rt
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/26531683/201289822-85392220-1442-463a-ac21-abeaaccb3cf6.png">
如图内，错误信息为当前弹窗内的batable提示，正确提示为父页面batable的删除操作。
如何避免在使用父页面batable时，弹窗内的batable不触发相同操作

**Comment by build-admin** [comment]
请更新框架，在新版本已对此相关进行了优化，且提供了"附件选择"的功能，该功能是一个弹窗内有baTable，可作为示例
